### ISSUE TITLE
authinfo.txt...

### ISSUE THREAD

**Issue by nmpx** [zavire-shiran/tumblrarchive#1]
Hey. So I'm finally kicking the tires on this but I'm not sure what I should be putting in the 'authinfo.txt' file....

I'm guessing my API key info but I'm not sure on formatting, etc.

**Comment by zavire-shiran** [comment]
I added a README, which hopefully answers your question. The relevant portion:

>For tumblrarchive to connect to tumblr's API, it needs to have some
login info. authinfo.txt is the place to store this data. Only the
first 4 lines of this file are used, and they should be in the order
expected by [PyTumblr](https://github.com/tumblr/pytumblr):

>```
<consumer_key>
<consumer_secret>
<oauth_token>
<oauth_secret>
```

>If you do not have these strings, the fastest way to get them is to
visit https://api.tumblr.com/console/

**Comment by nmpx** [comment]
Thanks! (Although I totally just distracted myself by writing a ruby script to do the archiving... lol. Sorry. I'll still test this out to see how it is).
